INSERT INTO MPA (NAME) VALUES ('G');
INSERT INTO MPA (NAME) VALUES ('PG');
INSERT INTO MPA (NAME) VALUES ('PG-13');
INSERT INTO MPA (NAME) VALUES ('R');
INSERT INTO MPA (NAME) VALUES ('NC-17');

INSERT INTO GENERE (NAME) VALUES ('Комедия');
INSERT INTO GENERE (NAME) VALUES ('Драма');
INSERT INTO GENERE (NAME) VALUES ('Мультфильм');
INSERT INTO GENERE (NAME) VALUES ('Триллер');
INSERT INTO GENERE (NAME) VALUES ('Документальный');
INSERT INTO GENERE (NAME) VALUES ('Боевик');
