INSERT INTO RATING (NAME) VALUES ('G');
INSERT INTO RATING (NAME) VALUES ('PG');
INSERT INTO RATING (NAME) VALUES ('PG-13');
INSERT INTO RATING (NAME) VALUES ('R');
INSERT INTO RATING (NAME) VALUES ('NC-17');

INSERT INTO GENERE (NAME) VALUES ('Comedy');
INSERT INTO GENERE (NAME) VALUES ('Drama');
INSERT INTO GENERE (NAME) VALUES ('CARTOON');
INSERT INTO GENERE (NAME) VALUES ('Thriller');
INSERT INTO GENERE (NAME) VALUES ('Documentary');
INSERT INTO GENERE (NAME) VALUES ('Smash-hit');